// Basic decomposition template
export const WORKSPACE_TEMPLATE = "WORKSPACE_TEMPLATE";

// Factored evaluation templates
export const JUDGE_WORKSPACE_TEMPLATE = "JUDGE_WORKSPACE_TEMPLATE";
export const HONEST_WORKSPACE_TEMPLATE = "HONEST_WORKSPACE_TEMPLATE";
export const MALICIOUS_WORKSPACE_TEMPLATE = "MALICIOUS_WORKSPACE_TEMPLATE";
